version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    network_mode: "host"
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["0.0.0.0:8888:8888"]
    network_mode: "host"
  redis:
    image: redis
    network_mode: "host"
  capsule:
    image: capsule_notebook
    network_mode: "host"
  ethermint:
    image: tendermint/ethermint
    network_mode: "host"
    volumes:
      - ".:/.ethermint"
    entrypoint: "/.ethermint/entrypoint.sh"
  tendermint:
      image: tendermint/tendermint
      network_mode: "host"
      volumes:
      - /tmp:/tendermint
      depends_on:
      - ethermint
